"""Add occurred_on to notification table

Revision ID: 148acde2b355
Revises: e34bd72c7373
Create Date: 2019-01-03 16:05:05.274109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '148acde2b355'
down_revision = 'e34bd72c7373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('occurred_on', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'occurred_on')
    # ### end Alembic commands ###
