"""Convert sequencing_run.run_date to date only

Revision ID: 1d84646fdf43
Revises: a8bd968890f2
Create Date: 2019-10-25 15:52:32.446994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d84646fdf43'
down_revision = 'a8bd968890f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sequencing_run', 'run_date',
               existing_type=mysql.DATETIME(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sequencing_run', 'run_date',
               existing_type=sa.DATE(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
