"""Create database tables

Revision ID: 3d41775a3046
Revises: 
Create Date: 2018-09-12 14:10:27.218661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d41775a3046'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('rnaseq_qc_report', sa.VARCHAR(length=255), nullable=True),
    sa.Column('wes_qc_report', sa.VARCHAR(length=255), nullable=True),
    sa.Column('xpress_project_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_job',
    sa.Column('project_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('id', sa.VARCHAR(length=45), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('command', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user', sa.VARCHAR(length=12), nullable=True),
    sa.Column('submitted_on', sa.DATETIME(), nullable=True),
    sa.Column('log_stream_name', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_job')
    op.drop_table('project')
    # ### end Alembic commands ###
