"""Add sequencing_run table

Revision ID: 4caad3cdf31e
Revises: 3d41775a3046
Create Date: 2018-10-12 16:47:53.321944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4caad3cdf31e'
down_revision = '3d41775a3046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequencing_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.DateTime, nullable=True),
    sa.Column('machine_id', sa.VARCHAR(length=25), nullable=True),
    sa.Column('run_number', sa.VARCHAR(length=5), nullable=True),
    sa.Column('flowcell_id', sa.VARCHAR(length=25), nullable=True),
    sa.Column('experiment_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('s3_run_folder_path', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequencing_run')
    # ### end Alembic commands ###
