"""Increase BatchJob command column length

Revision ID: 710f8f6c76dc
Revises: 148acde2b355
Create Date: 2019-07-24 20:17:43.657638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '710f8f6c76dc'
down_revision = '148acde2b355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("batch_job") as batch_op:
        batch_op.alter_column('command',
                existing_type=mysql.VARCHAR(length=255),
                type_=sa.VARCHAR(length=1024),
                existing_nullable=True)
        batch_op.alter_column('viewed',
                existing_type=mysql.TINYINT(display_width=1),
                type_=sa.BOOLEAN(),
                existing_nullable=False,
                existing_server_default=sa.text(u"'1'"))
    with op.batch_alter_table("notification") as batch_op:
        batch_op.alter_column('seen',
                existing_type=mysql.TINYINT(display_width=1),
                type_=sa.BOOLEAN(),
                existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification") as batch_op:
        batch_op.alter_column('seen',
                existing_type=sa.BOOLEAN(),
                type_=mysql.TINYINT(display_width=1),
                existing_nullable=True)
    with op.batch_alter_table("batch_job") as batch_op:
        batch_op.alter_column('viewed',
                existing_type=sa.BOOLEAN(),
                type_=mysql.TINYINT(display_width=1),
                existing_nullable=False,
                existing_server_default=sa.text(u"'1'"))
        batch_op.alter_column('command',
                existing_type=sa.VARCHAR(length=1024),
                type_=mysql.VARCHAR(length=255),
                existing_nullable=True)
    # ### end Alembic commands ###
