"""ProjectSample table

Revision ID: 921f4fc6f677
Revises: 1d84646fdf43
Create Date: 2019-11-08 05:45:44.818235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '921f4fc6f677'
down_revision = '1d84646fdf43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_sample')
    # ### end Alembic commands ###
