"""Add RunToSamples table

Revision ID: a8bd968890f2
Revises: 710f8f6c76dc
Create Date: 2019-10-02 22:22:44.303699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8bd968890f2'
down_revision = '710f8f6c76dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_to_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequencing_run_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.VARCHAR(length=512), nullable=True),
    sa.Column('project_id', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['sequencing_run_id'], ['sequencing_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_to_samples')
    # ### end Alembic commands ###
