"""Add Notification table

Revision ID: e34bd72c7373
Revises: b23863a37642
Create Date: 2019-01-02 17:43:58.746978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e34bd72c7373'
down_revision = 'b23863a37642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=12), nullable=True),
    sa.Column('batchjob_id', sa.VARCHAR(length=45), nullable=True),
    sa.Column('seen', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
